### PR TITLE
Feat: Added Auto Review Workflow for specific files and directories

### PR DESCRIPTION
**Pull request by Marty-Byrde**
This pull request introduces a new automated workflow for pull request reviews and sets up approval rules for specific files. The most important changes include the addition of a new GitHub Actions workflow and the configuration of approval rules for certain files.

Automated workflow setup:

* [`.github/workflows/auto-review-workflow.yml`](diffhunk://#diff-bbbd72706bff94c5295a755639f4bfca7267e17f650083daafc00f46a31072d7R1-R14): Added a new GitHub Actions workflow named "Auto PR Review" to automatically review pull requests using the `omio-labs/pr-reviewer-bot` action.

Approval rules configuration:

* [`.pr-bot.json`](diffhunk://#diff-0f699da466d3b43dfa43d2920a2df76e9684fc9ffcd795c7eb8d56e577e9542bR1-R9): Added a configuration file to specify approval rules, allowing changes to files within `.github/*`, `package.json`, and `yarn.lock`.

### CODE REVIEW

**Comment by Marty-Byrde** [comment]
Even if we use a personal access token with sufficient permissions, approvals made by automated processes (like GitHub Actions) will not count towards the required reviews specified in your branch protection rules. For that reason, this action is no longer needed, as it will not work as intended.

**Comment by Marty-Byrde** [comment]
After further research, browsing the settings showed that there is an option to enable GitHub actions to create and approve Pull request. Perhaps allowing this might make it possible.

**Review by Harvey-Reginald-Specter — DISMISSED** [review]
Automated approval based on allowed changes.

**Review by Harvey-Reginald-Specter — APPROVED** [review]
Good job! Your PR is auto-approved. Please merge once all tests have passed.

**Pull request merged**
